"""empty message

Revision ID: 2ed14dd41a7a
Revises: ee3d5a182419
Create Date: 2021-01-11 02:03:42.206061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed14dd41a7a'
down_revision = 'ee3d5a182419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
