"""empty message

Revision ID: ee3d5a182419
Revises: 
Create Date: 2021-01-11 02:02:31.112899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee3d5a182419'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Teacher_id', sa.Integer(), nullable=True),
    sa.Column('Student_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['Student_id'], ['Student.id'], ),
    sa.ForeignKeyConstraint(['Teacher_id'], ['Teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Homework')
    op.drop_table('Teacher')
    op.drop_table('Student')
    # ### end Alembic commands ###
