"""empty message

Revision ID: ef308e141eaa
Revises: 
Create Date: 2021-01-11 21:46:25.535837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef308e141eaa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Teacher',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Homework',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('deadline_date', sa.Date(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('HomeworkResult',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('homework_id', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['Student.id'], ),
    sa.ForeignKeyConstraint(['homework_id'], ['Homework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('HomeworkResult')
    op.drop_table('Homework')
    op.drop_table('Teacher')
    op.drop_table('Student')
    # ### end Alembic commands ###
